version: '3.8'

services:

  fitgogo:
    build:
      context: ./fitgogo
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./fitgogo:/app
    command: ["./main"]

  mongo:
    image: mongo:4.4.27-rc0
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
